"""Reconstruct frozen layouts from pinned archive members, without pip/network."""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import json
import shutil
import stat
import zipfile
from pathlib import Path

import pytest


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _fixture(tmp_path: Path, *, hex_record: bool = False) -> dict:
    site = tmp_path / "site-packages"
    dist = tmp_path / "frozen"
    cache = tmp_path / "cache"
    site.mkdir()
    dist.mkdir()
    cache.mkdir()
    info = "fixture_runtime-1.0.dist-info"
    wheel_files = {
        "vendor/bin/Qt6Core.dll": b"selected reviewed runtime DLL",
        f"{info}/METADATA": b"Metadata-Version: 2.1\nName: fixture-runtime\nVersion: 1.0\n",
        f"{info}/WHEEL": b"Wheel-Version: 1.0\nRoot-Is-Purelib: false\nTag: cp312-cp312-win_amd64\n",
    }
    rows = []
    for name, data in wheel_files.items():
        digest = (
            _sha(data)
            if hex_record
            else base64.urlsafe_b64encode(hashlib.sha256(data).digest()).decode().rstrip("=")
        )
        rows.append([name, f"sha256={digest}", len(data)])
    rows.append([f"{info}/RECORD", "", ""])
    record = io.StringIO(newline="")
    csv.writer(record).writerows(rows)
    wheel_files[f"{info}/RECORD"] = record.getvalue().encode()
    wheel = tmp_path / "fixture_runtime-1.0-cp312-cp312-win_amd64.whl"
    with zipfile.ZipFile(wheel, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in wheel_files.items():
            archive.writestr(name, data)
    for name, data in wheel_files.items():
        target = site / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    # These files are generated by the installer; a hashed installed RECORD
    # entry must not make them a candidate for a nonexistent wheel member.
    installer = site / info / "INSTALLER"
    installer.write_bytes(b"uv")
    with (site / info / "RECORD").open("a", newline="", encoding="utf-8") as stream:
        csv.writer(stream).writerow(
            [
                f"{info}/INSTALLER",
                "sha256="
                + base64.urlsafe_b64encode(hashlib.sha256(b"uv").digest()).decode().rstrip("="),
                2,
            ]
        )
    model = b"pinned STT weights fixture"
    frozen_files = {
        "InterviewAssistant.exe": b"private compiled executable",
        "_internal/Qt6Core.dll": wheel_files["vendor/bin/Qt6Core.dll"],
        "_internal/base_library.zip": b"build-specific stdlib",
        "_internal/assets/logo.ico": b"private logo",
        f"_internal/{info}/INSTALLER": b"uv",
        f"_internal/{info}/RECORD": (site / info / "RECORD").read_bytes(),
        "_internal/models/stt/fixture/model.bin": model,
    }
    entries = []
    for name, data in frozen_files.items():
        target = dist / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        entries.append({"path": name, "size": len(data), "sha256": _sha(data)})
    inventory = tmp_path / "inventory.json"
    inventory.write_text(
        json.dumps({"schema_version": 1, "application": "InterviewAssistant", "files": entries})
    )
    collect = tmp_path / "COLLECT-00.toc"
    collect.write_text(
        repr(
            (
                [
                    ("InterviewAssistant.exe", str(dist / "InterviewAssistant.exe"), "EXECUTABLE"),
                    ("Qt6Core.dll", str(site / "vendor/bin/Qt6Core.dll"), "BINARY"),
                    (f"{info}/INSTALLER", str(installer), "DATA"),
                    (f"{info}/RECORD", str(site / info / "RECORD"), "DATA"),
                ],
            )
        )
    )
    archive_hash = _sha(wheel.read_bytes())
    lock = tmp_path / "uv.lock"
    lock.write_text(f"""version = 1
[[package]]
name = "fixture-runtime"
version = "1.0"
source = {{registry = "https://pypi.org/simple"}}
wheels = [{{url = "https://files.pythonhosted.org/packages/fixture/{wheel.name}", hash = "sha256:{archive_hash}", size = {wheel.stat().st_size}}}]
""")
    model_manifest = tmp_path / "model.json"
    model_manifest.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "repository": "official-owner/model",
                "revision": "a" * 40,
                "bundle_subdirectory": "models/stt/fixture",
                "files": [{"path": "model.bin", "size": len(model), "sha256": _sha(model)}],
            }
        )
    )
    shutil.copyfile(wheel, cache / f"{archive_hash}.zip")
    (cache / f"{_sha(model)}.bin").write_bytes(model)
    return {
        "dist": dist,
        "inventory": inventory,
        "collect": collect,
        "lock": lock,
        "site_packages": site,
        "model_manifest": model_manifest,
        "cache": cache,
        "wheel": wheel,
    }


def _prepare(fixture: dict, *, verify: bool = False) -> dict:
    from scripts.prepare_online_payload import prepare_payload

    arguments = {k: v for k, v in fixture.items() if k not in ("cache", "wheel")}
    return prepare_payload(**arguments, verify_cache=fixture["cache"] if verify else None)


def test_exact_partition_preserves_relocated_dll_and_embeds_installer_metadata(
    tmp_path: Path,
) -> None:
    fixture = _fixture(tmp_path)
    payload = _prepare(fixture, verify=True)
    files = {entry["path"]: entry for entry in payload["files"]}
    expected = json.loads(fixture["inventory"].read_text())["files"]
    assert len(files) == len(expected) == len(payload["files"])
    assert all(files[e["path"]]["sha256"] == e["sha256"] for e in expected)
    dll = files["_internal/Qt6Core.dll"]
    assert dll["member"] == "vendor/bin/Qt6Core.dll"
    assert dll["artifact"].startswith("wheel-")
    assert files["InterviewAssistant.exe"]["artifact"] is None
    assert files["_internal/fixture_runtime-1.0.dist-info/INSTALLER"]["artifact"] is None
    assert files["_internal/fixture_runtime-1.0.dist-info/RECORD"]["artifact"] is None
    model = files["_internal/models/stt/fixture/model.bin"]
    assert model["member"] is None and model["artifact"].startswith("model-")
    assert payload["wheel_archives_verified"] is True
    assert payload["artifacts_verified"] is True
    wheel = next(a for a in payload["artifacts"] if a["kind"] == "wheel")
    with zipfile.ZipFile(fixture["wheel"]) as archive:
        assert wheel["expanded_size"] == sum(i.file_size for i in archive.infolist())
    assert next(a for a in payload["artifacts"] if a["kind"] == "file")["expanded_size"] == len(
        b"pinned STT weights fixture"
    )


def test_pending_manifest_does_not_claim_archives_verified(tmp_path: Path) -> None:
    payload = _prepare(_fixture(tmp_path))
    assert payload["wheel_archives_verified"] is False
    assert payload["artifacts_verified"] is False


def test_accepts_exact_upstream_hex_record_only_with_matching_content(tmp_path: Path) -> None:
    payload = _prepare(_fixture(tmp_path, hex_record=True), verify=True)
    assert next(e for e in payload["files"] if e["path"].endswith("Qt6Core.dll"))["artifact"]


def test_same_basename_from_unrecorded_source_stays_embedded(tmp_path: Path) -> None:
    fixture = _fixture(tmp_path)
    impostor = tmp_path / "other-application/Qt6Core.dll"
    impostor.parent.mkdir()
    impostor.write_bytes((fixture["dist"] / "_internal/Qt6Core.dll").read_bytes())
    fixture["collect"].write_text(repr(([("Qt6Core.dll", str(impostor), "BINARY")],)))
    payload = _prepare(fixture)
    assert (
        next(e for e in payload["files"] if e["path"].endswith("Qt6Core.dll"))["artifact"] is None
    )


@pytest.mark.parametrize("change", ["content", "extra", "missing", "duplicate"])
def test_rejects_inventory_drift(tmp_path: Path, change: str) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    if change == "content":
        (fixture["dist"] / "_internal/Qt6Core.dll").write_bytes(b"changed after review")
    elif change == "extra":
        (fixture["dist"] / "unexpected.txt").write_text("unexpected")
    elif change == "missing":
        (fixture["dist"] / "InterviewAssistant.exe").unlink()
    else:
        data = json.loads(fixture["inventory"].read_text())
        data["files"].append(dict(data["files"][0], path="interviewassistant.EXE"))
        fixture["inventory"].write_text(json.dumps(data))
    with pytest.raises(PayloadError, match="inventory"):
        _prepare(fixture)


@pytest.mark.parametrize(
    "path",
    [
        "../escape.dll",
        "C:/escape.dll",
        "_internal/a:stream",
        "_internal/CON.dll",
        "_internal/../bad",
        "_internal/{app}/bad",
    ],
)
def test_rejects_unsafe_windows_destination(tmp_path: Path, path: str) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    inventory = json.loads(fixture["inventory"].read_text())
    inventory["files"][0]["path"] = path
    fixture["inventory"].write_text(json.dumps(inventory))
    with pytest.raises(PayloadError, match="path"):
        _prepare(fixture)


@pytest.mark.parametrize(
    "url",
    [
        "http://files.pythonhosted.org/x",
        "https://evil.example/runtime.whl",
        "https://secret@files.pythonhosted.org/x",
        "https://files.pythonhosted.org/x?token=secret",
    ],
)
def test_rejects_unapproved_wheel_origin_without_echoing_url(tmp_path: Path, url: str) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    text = fixture["lock"].read_text()
    old = f"https://files.pythonhosted.org/packages/fixture/{fixture['wheel'].name}"
    fixture["lock"].write_text(
        text.replace(
            old,
            url.rsplit("/", 1)[0]
            + "/"
            + fixture["wheel"].name
            + ("?token=secret" if "?" in url else ""),
        )
    )
    with pytest.raises(PayloadError, match="URL") as error:
        _prepare(fixture)
    assert "secret" not in str(error.value)


def test_unpinned_distribution_remains_embedded(tmp_path: Path) -> None:
    fixture = _fixture(tmp_path)
    fixture["lock"].write_text("version = 1\n")
    payload = _prepare(fixture)
    assert (
        next(e for e in payload["files"] if e["path"].endswith("Qt6Core.dll"))["artifact"] is None
    )


@pytest.mark.parametrize("artifact_kind", ["wheel", "model"])
def test_corrupt_cached_download_fails_before_outputs(tmp_path: Path, artifact_kind: str) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    cached = next(fixture["cache"].glob("*.zip" if artifact_kind == "wheel" else "*.bin"))
    cached.write_bytes(b"corrupted")
    with pytest.raises(PayloadError, match="cache"):
        _prepare(fixture, verify=True)


def test_archive_member_must_match_reviewed_frozen_bytes(tmp_path: Path) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    # A fully pinned archive digest is insufficient when the selected member
    # does not match the already reviewed portable file.
    payload = _prepare(fixture)
    artifact = next(a for a in payload["artifacts"] if a["kind"] == "wheel")
    with zipfile.ZipFile(fixture["wheel"], "w") as archive:
        archive.writestr("vendor/bin/Qt6Core.dll", b"different wheel content")
    previous = artifact["sha256"]
    updated = _sha(fixture["wheel"].read_bytes())
    fixture["lock"].write_text(
        fixture["lock"]
        .read_text()
        .replace(previous, updated)
        .replace(f"size = {artifact['size']}", f"size = {fixture['wheel'].stat().st_size}")
    )
    shutil.copyfile(fixture["wheel"], fixture["cache"] / f"{updated}.zip")
    with pytest.raises(PayloadError, match="member"):
        _prepare(fixture, verify=True)


def test_inno_includes_preserve_paths_and_external_indexing(tmp_path: Path) -> None:
    from scripts.prepare_online_payload import write_outputs

    payload = _prepare(_fixture(tmp_path), verify=True)
    output = tmp_path / "output"
    write_outputs(payload, output)
    files = (output / "payload_files.iss").read_text(encoding="utf-8-sig")
    data = (output / "payload_data.iss").read_text(encoding="utf-8-sig")
    assert "[Files]" not in files
    assert 'Source: "{#DistPath}\\InterviewAssistant.exe"' in files
    assert 'Source: "{code:GetPreparedFile|0}"' in files
    assert 'DestDir: "{app}\\_internal"; DestName: "Qt6Core.dll"' in files
    assert "Flags: external ignoreversion" in files
    assert "SetArrayLength(PayloadFiles, 2);" in data
    assert "MemberPath := 'vendor\\bin\\Qt6Core.dll'" in data
    assert "procedure LoadOnlinePayload;" in data
    assert ".ExpandedSize := " in data
    assert "payload_manifest_sha256=" in files and "payload_manifest_sha256=" in data
    assert json.loads((output / "online_payload.json").read_text())["artifacts_verified"] is True


def test_unpinned_model_revision_rejected(tmp_path: Path) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    model = json.loads(fixture["model_manifest"].read_text())
    model["revision"] = "main"
    fixture["model_manifest"].write_text(json.dumps(model))
    with pytest.raises(PayloadError, match="revision"):
        _prepare(fixture)


@pytest.mark.parametrize("unsafe", ["../escape.dll", "vendor/BIN/qt6core.DLL", "symlink"])
def test_rejects_unsafe_unselected_archive_members_before_extraction(
    tmp_path: Path, unsafe: str
) -> None:
    from scripts.prepare_online_payload import PayloadError

    fixture = _fixture(tmp_path)
    payload = _prepare(fixture)
    artifact = next(a for a in payload["artifacts"] if a["kind"] == "wheel")
    with zipfile.ZipFile(fixture["wheel"], "a") as archive:
        if unsafe == "symlink":
            link = zipfile.ZipInfo("vendor/link")
            link.create_system = 3
            link.external_attr = (stat.S_IFLNK | 0o777) << 16
            archive.writestr(link, "../outside")
        else:
            archive.writestr(unsafe, "unselected content")
    digest = _sha(fixture["wheel"].read_bytes())
    fixture["lock"].write_text(
        fixture["lock"]
        .read_text()
        .replace(artifact["sha256"], digest)
        .replace(f"size = {artifact['size']}", f"size = {fixture['wheel'].stat().st_size}")
    )
    shutil.copyfile(fixture["wheel"], fixture["cache"] / f"{digest}.zip")
    with pytest.raises(PayloadError, match="path|member"):
        _prepare(fixture, verify=True)
    assert not (tmp_path / "escape.dll").exists()


def test_mismatched_installed_record_stays_embedded(tmp_path: Path) -> None:
    fixture = _fixture(tmp_path)
    record = fixture["site_packages"] / "fixture_runtime-1.0.dist-info/RECORD"
    text = record.read_text()
    original = text.splitlines()[0]
    record.write_text(text.replace(original, "vendor/bin/Qt6Core.dll,sha256=" + "a" * 64 + ",29"))
    payload = _prepare(fixture)
    assert (
        next(e for e in payload["files"] if e["path"].endswith("Qt6Core.dll"))["artifact"] is None
    )


def test_pending_outputs_can_be_replaced_with_verified_outputs(tmp_path: Path) -> None:
    from scripts.prepare_online_payload import write_outputs

    fixture = _fixture(tmp_path)
    output = tmp_path / "generated"
    write_outputs(_prepare(fixture), output)
    assert not json.loads((output / "online_payload.json").read_text())["artifacts_verified"]
    write_outputs(_prepare(fixture, verify=True), output)
    assert json.loads((output / "online_payload.json").read_text())["artifacts_verified"]
    assert not list(output.glob("*.tmp"))
